"""MLB predictive-modeling helpers."""

from plugins.mlb_modeling.public_sources import (
    AvailabilityStatus,
    DataSourceSnapshot,
    MLBEnvironmentFeatureBuilder,
    MLBMarketSignalBuilder,
    MLBTravelFatigueBuilder,
    UnavailablePublicSignalAdapter,
)
from plugins.mlb_modeling.features import (
    BullpenFatigueSummary,
    MLBFeatureRepository,
    RelieverAppearance,
    build_advanced_feature_payload,
    calculate_bullpen_fatigue,
    get_recent_bullpen_appearances,
    recency_weighted_average,
    stable_feature_hash,
)
from plugins.mlb_modeling.models import (
    BinaryCalibrationMetrics,
    CalibratedMoneylineModel,
    DEFAULT_MONEYLINE_MODEL_PATH,
    MoneylineModelArtifact,
    MoneylineTrainingRow,
    artifact_passes_gate,
    evaluate_binary_predictions,
    load_moneyline_model_artifact,
    save_moneyline_model_artifact,
    train_logistic_moneyline_model,
    validate_runtime_feature_inputs,
)
from plugins.mlb_modeling.props import (
    PAOutcomeProbabilities,
    PropPredictionBuilder,
    build_pa_outcome_probabilities,
    empirical_bayes_rate,
    log5_probability,
)
from plugins.mlb_modeling.simulation import (
    MLBGameSimulationResult,
    MLBMonteCarloSimulator,
)
from plugins.mlb_modeling.matchup_assembler import (
    MatchupAssemblyConfig,
    assemble_matchup_features,
)
from plugins.mlb_modeling.validation import (
    MLBValidationGateConfig,
    MLBValidationGateResult,
    MLBValidationSnapshot,
    evaluate_validation_gates,
)
from plugins.mlb_modeling.airflow_tasks import (
    MODEL_ARTIFACT_UNAVAILABLE_REASON,
    PUBLIC_MONEYLINE_MODEL_VERSION,
    build_abstaining_moneyline_payloads,
    score_mlb_moneyline_model,
)
from plugins.mlb_modeling.evidence import (
    BettingEvidenceMetrics,
    EloBacktestConfig,
    ModelEvidenceMetrics,
    ModelImprovementDelta,
    audit_clv_snapshot_fidelity,
    build_betting_evidence_frame,
    build_value_recommendations,
    compute_betting_evidence_metrics,
    compare_model_metrics,
    evaluate_prediction_records,
    expected_calibration_error,
    run_elo_backtest,
    run_standard_elo_improvement_backtest,
    summarize_betting_evidence_by_edge_bucket,
)
from plugins.mlb_modeling.player_stats_fetcher import (
    MLBPlayerStatsFetcher,
    PlayerStatsFetchResult,
    compute_advanced_batting_metrics,
    compute_advanced_pitching_metrics,
    fetch_player_stats,
    upsert_batting_stats,
    upsert_pitching_stats,
    upsert_pitch_features,
)

__all__ = [
    "AvailabilityStatus",
    "BullpenFatigueSummary",
    "DataSourceSnapshot",
    "DEFAULT_MONEYLINE_MODEL_PATH",
    "MLBFeatureRepository",
    "MLBEnvironmentFeatureBuilder",
    "MLBMarketSignalBuilder",
    "MLBTravelFatigueBuilder",
    "MLBGameSimulationResult",
    "MLBMonteCarloSimulator",
    "MLBValidationGateConfig",
    "MLBValidationGateResult",
    "MLBValidationSnapshot",
    "MODEL_ARTIFACT_UNAVAILABLE_REASON",
    "ModelEvidenceMetrics",
    "ModelImprovementDelta",
    "PAOutcomeProbabilities",
    "PUBLIC_MONEYLINE_MODEL_VERSION",
    "PropPredictionBuilder",
    "RelieverAppearance",
    "UnavailablePublicSignalAdapter",
    "build_advanced_feature_payload",
    "build_abstaining_moneyline_payloads",
    "build_pa_outcome_probabilities",
    "BinaryCalibrationMetrics",
    "BettingEvidenceMetrics",
    "audit_clv_snapshot_fidelity",
    "build_betting_evidence_frame",
    "build_value_recommendations",
    "CalibratedMoneylineModel",
    "compute_betting_evidence_metrics",
    "compare_model_metrics",
    "EloBacktestConfig",
    "calculate_bullpen_fatigue",
    "get_recent_bullpen_appearances",
    "empirical_bayes_rate",
    "evaluate_prediction_records",
    "MoneylineModelArtifact",
    "MoneylineTrainingRow",
    "artifact_passes_gate",
    "assemble_matchup_features",
    "evaluate_binary_predictions",
    "expected_calibration_error",
    "evaluate_validation_gates",
    "log5_probability",
    "MatchupAssemblyConfig",
    "recency_weighted_average",
    "run_elo_backtest",
    "run_standard_elo_improvement_backtest",
    "load_moneyline_model_artifact",
    "save_moneyline_model_artifact",
    "score_mlb_moneyline_model",
    "stable_feature_hash",
    "summarize_betting_evidence_by_edge_bucket",
    "train_logistic_moneyline_model",
    "validate_runtime_feature_inputs",
    # player_stats_fetcher
    "MLBPlayerStatsFetcher",
    "PlayerStatsFetchResult",
    "compute_advanced_batting_metrics",
    "compute_advanced_pitching_metrics",
    "fetch_player_stats",
    "upsert_batting_stats",
    "upsert_pitching_stats",
    "upsert_pitch_features",
]
