from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class NamingContext:
    """Context for resolving a team or player name."""

    sport: str
    source: str
    name: str

    def to_key(self) -> tuple:
        """Return the lookup key for this context."""
        return (self.sport.lower(), self.source.lower(), self.name.lower())


class NamingResolver:
    # Class-level mapping storage
    _mappings = {
        # NCAAB
        ("ncaab", "kalshi", "hou"): "Houston",
        ("ncaab", "kalshi", "pur"): "Purdue",
        ("ncaab", "kalshi", "aub"): "Auburn",
        ("ncaab", "kalshi", "ala"): "Alabama",
        ("ncaab", "kalshi", "byu"): "BYU",
        ("ncaab", "kalshi", "uga"): "Georgia",
        ("ncaab", "kalshi", "lsu"): "LSU",
        ("ncaab", "kalshi", "day"): "Dayton",
        ("ncaab", "kalshi", "vcu"): "VCU",
        ("ncaab", "kalshi", "kan"): "Kansas",
        ("ncaab", "kalshi", "ken"): "Kentucky",
        ("ncaab", "kalshi", "duk"): "Duke",
        ("ncaab", "kalshi", "unc"): "North_Carolina",
        ("ncaab", "kalshi", "az"): "Arizona",
        ("ncaab", "kalshi", "gonz"): "Gonzaga",
        ("ncaab", "kalshi", "conn"): "Connecticut",
        ("ncaab", "kalshi", "tenn"): "Tennessee",
        ("ncaab", "kalshi", "isu"): "Iowa_St",
        ("ncaab", "kalshi", "bay"): "Baylor",
        ("ncaab", "kalshi", "ore"): "Oregon",
        ("ncaab", "kalshi", "ksu"): "Kansas_St",
        ("ncaab", "kalshi", "fiu"): "Florida_Intl",
        ("ncaab", "kalshi", "tcu"): "TCU",
        ("ncaab", "kalshi", "wis"): "Wisconsin",
        ("ncaab", "kalshi", "ind"): "Indiana",
        ("ncaab", "kalshi", "wku"): "Western_Kentucky",
        ("ncaab", "kalshi", "slu"): "Saint_Louis",
        ("ncaab", "kalshi", "uvm"): "Vermont",
        ("ncaab", "kalshi", "sfa"): "Stephen_F._Austin",
        ("ncaab", "kalshi", "lmu"): "Loyola_Marymount",
        ("ncaab", "kalshi", "quc"): "Queens_University",
        ("ncaab", "kalshi", "app"): "Appalachian_St",
        ("ncaab", "kalshi", "und"): "North_Dakota",
        ("ncaab", "kalshi", "cin"): "Cincinnati",
        ("ncaab", "kalshi", "wvu"): "West_Virginia",
        ("ncaab", "kalshi", "tex"): "Texas",
        # Add ELO mappings for canonical lookup
        ("ncaab", "elo", "houston"): "Houston",
        ("ncaab", "elo", "purdue"): "Purdue",
        ("ncaab", "elo", "auburn"): "Auburn",
        ("ncaab", "elo", "alabama"): "Alabama",
        ("ncaab", "elo", "byu"): "BYU",
        ("ncaab", "elo", "georgia"): "Georgia",
        ("ncaab", "elo", "lsu"): "LSU",
        ("ncaab", "elo", "dayton"): "Dayton",
        ("ncaab", "elo", "vcu"): "VCU",
        ("ncaab", "elo", "kansas"): "Kansas",
        ("ncaab", "elo", "kentucky"): "Kentucky",
        ("ncaab", "elo", "duke"): "Duke",
        ("ncaab", "elo", "north_carolina"): "North_Carolina",
        ("ncaab", "elo", "arizona"): "Arizona",
        ("ncaab", "elo", "gonzaga"): "Gonzaga",
        ("ncaab", "elo", "connecticut"): "Connecticut",
        ("ncaab", "elo", "tennessee"): "Tennessee",
        ("ncaab", "elo", "iowa_st"): "Iowa_St",
        ("ncaab", "elo", "baylor"): "Baylor",
        ("ncaab", "elo", "oregon"): "Oregon",
        ("ncaab", "elo", "kansas_st"): "Kansas_St",
        ("ncaab", "elo", "florida_intl"): "Florida_Intl",
        ("ncaab", "elo", "tcu"): "TCU",
        ("ncaab", "elo", "wisconsin"): "Wisconsin",
        ("ncaab", "elo", "indiana"): "Indiana",
        ("ncaab", "elo", "western_kentucky"): "Western_Kentucky",
        ("ncaab", "elo", "saint_louis"): "Saint_Louis",
        ("ncaab", "elo", "vermont"): "Vermont",
        ("ncaab", "elo", "stephen_f._austin"): "Stephen_F._Austin",
        ("ncaab", "elo", "loyola_marymount"): "Loyola_Marymount",
        ("ncaab", "elo", "queens_university"): "Queens_University",
        ("ncaab", "elo", "appalachian_st"): "Appalachian_St",
        ("ncaab", "elo", "north_dakota"): "North_Dakota",
        ("ncaab", "elo", "cincinnati"): "Cincinnati",
        ("ncaab", "elo", "west_virginia"): "West_Virginia",
        ("ncaab", "elo", "texas"): "Texas",
        # WNCAAB (using common abbreviations from Kalshi)
        ("wncaab", "kalshi", "van"): "Vanderbilt",
        ("wncaab", "kalshi", "fla"): "Florida",
        ("wncaab", "kalshi", "ark"): "Arkansas",
        ("wncaab", "kalshi", "aub"): "Auburn",
        ("wncaab", "kalshi", "lsu"): "LSU",
        ("wncaab", "kalshi", "tex"): "Texas",
        ("wncaab", "kalshi", "ala"): "Alabama",
        ("wncaab", "kalshi", "miss"): "Ole_Miss",
        ("wncaab", "kalshi", "msu"): "Mississippi_St",
        ("wncaab", "kalshi", "tenn"): "Tennessee",
        ("wncaab", "kalshi", "sc"): "South_Carolina",
        ("wncaab", "kalshi", "uk"): "Kentucky",
        ("wncaab", "kalshi", "uga"): "Georgia",
        ("wncaab", "kalshi", "mizz"): "Missouri",
        ("wncaab", "kalshi", "tamu"): "Texas_A&M",
        # WNCAAB ELO
        ("wncaab", "elo", "vanderbilt"): "Vanderbilt",
        ("wncaab", "elo", "florida"): "Florida",
        ("wncaab", "elo", "arkansas"): "Arkansas",
        ("wncaab", "elo", "auburn"): "Auburn",
        ("wncaab", "elo", "lsu"): "LSU",
        ("wncaab", "elo", "texas"): "Texas",
        ("wncaab", "elo", "alabama"): "Alabama",
        ("wncaab", "elo", "ole_miss"): "Ole_Miss",
        ("wncaab", "elo", "mississippi_st"): "Mississippi_St",
        ("wncaab", "elo", "tennessee"): "Tennessee",
        ("wncaab", "elo", "south_carolina"): "South_Carolina",
        ("wncaab", "elo", "kentucky"): "Kentucky",
        ("wncaab", "elo", "georgia"): "Georgia",
        ("wncaab", "elo", "missouri"): "Missouri",
        ("wncaab", "elo", "texas_a&m"): "Texas_A&M",
        # EPL
        ("epl", "kalshi", "ars"): "Arsenal",
        ("epl", "kalshi", "arsenal"): "Arsenal",
        ("epl", "kalshi", "avl"): "Aston Villa",
        ("epl", "kalshi", "aston villa"): "Aston Villa",
        ("epl", "kalshi", "bou"): "Bournemouth",
        ("epl", "kalshi", "bournemouth"): "Bournemouth",
        ("epl", "kalshi", "bre"): "Brentford",
        ("epl", "kalshi", "brentford"): "Brentford",
        ("epl", "kalshi", "bri"): "Brighton",
        ("epl", "kalshi", "bha"): "Brighton",
        ("epl", "kalshi", "brighton"): "Brighton",
        ("epl", "kalshi", "brighton and hove albion"): "Brighton",
        ("epl", "kalshi", "brighton & hove albion"): "Brighton",
        ("epl", "kalshi", "bur"): "Burnley",
        ("epl", "kalshi", "burnley"): "Burnley",
        ("epl", "kalshi", "cfc"): "Chelsea",
        ("epl", "kalshi", "che"): "Chelsea",
        ("epl", "kalshi", "chelsea"): "Chelsea",
        ("epl", "kalshi", "cry"): "Crystal Palace",
        ("epl", "kalshi", "crystal palace"): "Crystal Palace",
        ("epl", "kalshi", "eve"): "Everton",
        ("epl", "kalshi", "everton"): "Everton",
        ("epl", "kalshi", "ful"): "Fulham",
        ("epl", "kalshi", "fulham"): "Fulham",
        ("epl", "kalshi", "ips"): "Ipswich",
        ("epl", "kalshi", "ipswich"): "Ipswich",
        ("epl", "kalshi", "ipswich town"): "Ipswich",
        ("epl", "kalshi", "lee"): "Leeds",
        ("epl", "kalshi", "leeds"): "Leeds",
        ("epl", "kalshi", "leeds united"): "Leeds",
        ("epl", "kalshi", "lei"): "Leicester",
        ("epl", "kalshi", "leicester"): "Leicester",
        ("epl", "kalshi", "leicester city"): "Leicester",
        ("epl", "kalshi", "lfc"): "Liverpool",
        ("epl", "kalshi", "liverpool"): "Liverpool",
        ("epl", "kalshi", "lut"): "Luton",
        ("epl", "kalshi", "luton"): "Luton",
        ("epl", "kalshi", "luton town"): "Luton",
        ("epl", "kalshi", "mci"): "Man City",
        ("epl", "kalshi", "man city"): "Man City",
        ("epl", "kalshi", "manchester city"): "Man City",
        ("epl", "kalshi", "mun"): "Man United",
        ("epl", "kalshi", "man united"): "Man United",
        ("epl", "kalshi", "manchester united"): "Man United",
        ("epl", "kalshi", "new"): "Newcastle",
        ("epl", "kalshi", "newcastle"): "Newcastle",
        ("epl", "kalshi", "newcastle united"): "Newcastle",
        ("epl", "kalshi", "nfo"): "Nott'm Forest",
        ("epl", "kalshi", "not"): "Nott'm Forest",
        ("epl", "kalshi", "nott'm forest"): "Nott'm Forest",
        ("epl", "kalshi", "nottingham"): "Nott'm Forest",
        ("epl", "kalshi", "nottingham forest"): "Nott'm Forest",
        ("epl", "kalshi", "nor"): "Norwich",
        ("epl", "kalshi", "norwich"): "Norwich",
        ("epl", "kalshi", "norwich city"): "Norwich",
        ("epl", "kalshi", "shu"): "Sheffield United",
        ("epl", "kalshi", "sheffield united"): "Sheffield United",
        ("epl", "kalshi", "sheffield utd"): "Sheffield United",
        ("epl", "kalshi", "sou"): "Southampton",
        ("epl", "kalshi", "southampton"): "Southampton",
        ("epl", "kalshi", "sun"): "Sunderland",
        ("epl", "kalshi", "sunderland"): "Sunderland",
        ("epl", "kalshi", "tot"): "Tottenham",
        ("epl", "kalshi", "tottenham"): "Tottenham",
        ("epl", "kalshi", "tottenham hotspur"): "Tottenham",
        ("epl", "kalshi", "wat"): "Watford",
        ("epl", "kalshi", "watford"): "Watford",
        ("epl", "kalshi", "whu"): "West Ham",
        ("epl", "kalshi", "west ham"): "West Ham",
        ("epl", "kalshi", "west ham united"): "West Ham",
        ("epl", "kalshi", "wol"): "Wolves",
        ("epl", "kalshi", "wolverhampton"): "Wolves",
        ("epl", "kalshi", "wolves"): "Wolves",
        ("epl", "kalshi", "wolverhampton wanderers"): "Wolves",
        # NBA
        ("nba", "kalshi", "atl"): "ATL",
        ("nba", "kalshi", "atlanta"): "ATL",
        ("nba", "kalshi", "atlanta hawks"): "ATL",
        ("nba", "kalshi", "atlanta braves"): "ATL",
        ("nba", "kalshi", "bkn"): "BKN",
        ("nba", "kalshi", "brooklyn"): "BKN",
        ("nba", "kalshi", "brooklyn nets"): "BKN",
        ("nba", "kalshi", "nets"): "BKN",
        ("nba", "kalshi", "bos"): "BOS",
        ("nba", "kalshi", "boston"): "BOS",
        ("nba", "kalshi", "boston celtics"): "BOS",
        ("nba", "kalshi", "celtics"): "BOS",
        ("nba", "kalshi", "cha"): "CHA",
        ("nba", "kalshi", "charlotte"): "CHA",
        ("nba", "kalshi", "charlotte hornets"): "CHA",
        ("nba", "kalshi", "hornets"): "CHA",
        ("nba", "kalshi", "chi"): "CHI",
        ("nba", "kalshi", "chicago"): "CHI",
        ("nba", "kalshi", "chicago bulls"): "CHI",
        ("nba", "kalshi", "bulls"): "CHI",
        ("nba", "kalshi", "cle"): "CLE",
        ("nba", "kalshi", "cleveland"): "CLE",
        ("nba", "kalshi", "cleveland cavaliers"): "CLE",
        ("nba", "kalshi", "cleveland guardians"): "CLE",
        ("nba", "kalshi", "cavaliers"): "CLE",
        ("nba", "kalshi", "dal"): "DAL",
        ("nba", "kalshi", "dallas"): "DAL",
        ("nba", "kalshi", "dallas mavericks"): "DAL",
        ("nba", "kalshi", "mavericks"): "DAL",
        ("nba", "kalshi", "den"): "DEN",
        ("nba", "kalshi", "denver"): "DEN",
        ("nba", "kalshi", "denver nuggets"): "DEN",
        ("nba", "kalshi", "nuggets"): "DEN",
        ("nba", "kalshi", "det"): "DET",
        ("nba", "kalshi", "detroit"): "DET",
        ("nba", "kalshi", "detroit pistons"): "DET",
        ("nba", "kalshi", "pistons"): "DET",
        ("nba", "kalshi", "gsw"): "GSW",
        ("nba", "kalshi", "golden state"): "GSW",
        ("nba", "kalshi", "goldenstate"): "GSW",
        ("nba", "kalshi", "golden state warriors"): "GSW",
        ("nba", "kalshi", "warriors"): "GSW",
        ("nba", "kalshi", "hou"): "HOU",
        ("nba", "kalshi", "houston"): "HOU",
        ("nba", "kalshi", "houston rockets"): "HOU",
        ("nba", "kalshi", "rockets"): "HOU",
        ("nba", "kalshi", "ind"): "IND",
        ("nba", "kalshi", "indiana"): "IND",
        ("nba", "kalshi", "indiana pacers"): "IND",
        ("nba", "kalshi", "pacers"): "IND",
        ("nba", "kalshi", "lac"): "LAC",
        ("nba", "kalshi", "los angeles c"): "LAC",
        ("nba", "kalshi", "la clippers"): "LAC",
        ("nba", "kalshi", "los angeles clippers"): "LAC",
        ("nba", "kalshi", "clippers"): "LAC",
        ("nba", "kalshi", "lal"): "LAL",
        ("nba", "kalshi", "los angeles l"): "LAL",
        ("nba", "kalshi", "la lakers"): "LAL",
        ("nba", "kalshi", "los angeles lakers"): "LAL",
        ("nba", "kalshi", "lakers"): "LAL",
        ("nba", "kalshi", "mem"): "MEM",
        ("nba", "kalshi", "memphis"): "MEM",
        ("nba", "kalshi", "memphis grizzlies"): "MEM",
        ("nba", "kalshi", "grizzlies"): "MEM",
        ("nba", "kalshi", "mia"): "MIA",
        ("nba", "kalshi", "miami"): "MIA",
        ("nba", "kalshi", "miami heat"): "MIA",
        ("nba", "kalshi", "miami marlins"): "MIA",
        ("nba", "kalshi", "heat"): "MIA",
        ("nba", "kalshi", "mil"): "MIL",
        ("nba", "kalshi", "milwaukee"): "MIL",
        ("nba", "kalshi", "milwaukee bucks"): "MIL",
        ("nba", "kalshi", "bucks"): "MIL",
        ("nba", "kalshi", "min"): "MIN",
        ("nba", "kalshi", "minnesota"): "MIN",
        ("nba", "kalshi", "minnesota timberwolves"): "MIN",
        ("nba", "kalshi", "timberwolves"): "MIN",
        ("nba", "kalshi", "nop"): "NOP",
        ("nba", "kalshi", "new orleans"): "NOP",
        ("nba", "kalshi", "neworleans"): "NOP",
        ("nba", "kalshi", "new orleans pelicans"): "NOP",
        ("nba", "kalshi", "pelicans"): "NOP",
        ("nba", "kalshi", "nyk"): "NYK",
        ("nba", "kalshi", "new york"): "NYK",
        ("nba", "kalshi", "newyork"): "NYK",
        ("nba", "kalshi", "new york knicks"): "NYK",
        ("nba", "kalshi", "knicks"): "NYK",
        ("nba", "kalshi", "okc"): "OKC",
        ("nba", "kalshi", "oklahoma city"): "OKC",
        ("nba", "kalshi", "oklahomacity"): "OKC",
        ("nba", "kalshi", "oklahoma city thunder"): "OKC",
        ("nba", "kalshi", "thunder"): "OKC",
        ("nba", "kalshi", "orl"): "ORL",
        ("nba", "kalshi", "orlando"): "ORL",
        ("nba", "kalshi", "orlando magic"): "ORL",
        ("nba", "kalshi", "magic"): "ORL",
        ("nba", "kalshi", "phi"): "PHI",
        ("nba", "kalshi", "philadelphia"): "PHI",
        ("nba", "kalshi", "philadelphia 76ers"): "PHI",
        ("nba", "kalshi", "76ers"): "PHI",
        ("nba", "kalshi", "phx"): "PHX",
        ("nba", "kalshi", "phoenix"): "PHX",
        ("nba", "kalshi", "phoenix suns"): "PHX",
        ("nba", "kalshi", "suns"): "PHX",
        ("nba", "kalshi", "por"): "POR",
        ("nba", "kalshi", "portland"): "POR",
        ("nba", "kalshi", "portland trail blazers"): "POR",
        ("nba", "kalshi", "trail blazers"): "POR",
        ("nba", "kalshi", "trail_blazers"): "POR",
        ("nba", "kalshi", "sac"): "SAC",
        ("nba", "kalshi", "sacramento"): "SAC",
        ("nba", "kalshi", "sacramento kings"): "SAC",
        ("nba", "kalshi", "kings"): "SAC",
        ("nba", "kalshi", "sas"): "SAS",
        ("nba", "kalshi", "san antonio"): "SAS",
        ("nba", "kalshi", "sanantonio"): "SAS",
        ("nba", "kalshi", "san antonio spurs"): "SAS",
        ("nba", "kalshi", "spurs"): "SAS",
        ("nba", "kalshi", "tor"): "TOR",
        ("nba", "kalshi", "toronto"): "TOR",
        ("nba", "kalshi", "toronto raptors"): "TOR",
        ("nba", "kalshi", "raptors"): "TOR",
        ("nba", "kalshi", "uta"): "UTA",
        ("nba", "kalshi", "utah"): "UTA",
        ("nba", "kalshi", "utah jazz"): "UTA",
        ("nba", "kalshi", "jazz"): "UTA",
        ("nba", "kalshi", "was"): "WAS",
        ("nba", "kalshi", "washington"): "WAS",
        ("nba", "kalshi", "washington wizards"): "WAS",
        ("nba", "kalshi", "wizards"): "WAS",
        # NHL
        ("nhl", "kalshi", "ana"): "ANA",
        ("nhl", "kalshi", "ari"): "ARI",
        ("nhl", "kalshi", "bos"): "BOS",
        ("nhl", "kalshi", "buf"): "BUF",
        ("nhl", "kalshi", "cgy"): "CGY",
        ("nhl", "kalshi", "car"): "CAR",
        ("nhl", "kalshi", "chi"): "CHI",
        ("nhl", "kalshi", "col"): "COL",
        ("nhl", "kalshi", "cbj"): "CBJ",
        ("nhl", "kalshi", "dal"): "DAL",
        ("nhl", "kalshi", "det"): "DET",
        ("nhl", "kalshi", "edm"): "EDM",
        ("nhl", "kalshi", "fla"): "FLA",
        ("nhl", "kalshi", "la"): "LAK",
        ("nhl", "kalshi", "lak"): "LAK",
        ("nhl", "kalshi", "min"): "MIN",
        ("nhl", "kalshi", "mtl"): "MTL",
        ("nhl", "kalshi", "nj"): "NJD",
        ("nhl", "kalshi", "nsh"): "NSH",
        ("nhl", "kalshi", "njd"): "NJD",
        ("nhl", "kalshi", "nyi"): "NYI",
        ("nhl", "kalshi", "nyr"): "NYR",
        ("nhl", "kalshi", "ott"): "OTT",
        ("nhl", "kalshi", "phi"): "PHI",
        ("nhl", "kalshi", "pit"): "PIT",
        ("nhl", "kalshi", "sj"): "SJS",
        ("nhl", "kalshi", "sjs"): "SJS",
        ("nhl", "kalshi", "sea"): "SEA",
        ("nhl", "kalshi", "stl"): "STL",
        ("nhl", "kalshi", "tb"): "TBL",
        ("nhl", "kalshi", "tbl"): "TBL",
        ("nhl", "kalshi", "tor"): "TOR",
        ("nhl", "kalshi", "uta"): "UTA",
        ("nhl", "kalshi", "van"): "VAN",
        ("nhl", "kalshi", "vgk"): "VGK",
        ("nhl", "kalshi", "wsh"): "WSH",
        ("nhl", "kalshi", "wpg"): "WPG",
        # NHL ELO / Canonical Mappings
        ("nhl", "elo", "anaheim ducks"): "ANA",
        ("nhl", "elo", "anaheim"): "ANA",
        ("nhl", "elo", "arizona coyotes"): "UTA",  # relocated to Utah (2024)
        ("nhl", "elo", "arizona"): "UTA",
        ("nhl", "elo", "boston bruins"): "BOS",
        ("nhl", "elo", "boston"): "BOS",
        ("nhl", "elo", "buffalo sabres"): "BUF",
        ("nhl", "elo", "buffalo"): "BUF",
        ("nhl", "elo", "calgary flames"): "CGY",
        ("nhl", "elo", "calgary"): "CGY",
        ("nhl", "elo", "carolina hurricanes"): "CAR",
        ("nhl", "elo", "carolina"): "CAR",
        ("nhl", "elo", "chicago blackhawks"): "CHI",
        ("nhl", "elo", "chicago"): "CHI",
        ("nhl", "elo", "colorado avalanche"): "COL",
        ("nhl", "elo", "colorado"): "COL",
        ("nhl", "elo", "columbus blue jackets"): "CBJ",
        ("nhl", "elo", "columbus"): "CBJ",
        ("nhl", "elo", "dallas stars"): "DAL",
        ("nhl", "elo", "dallas"): "DAL",
        ("nhl", "elo", "detroit red wings"): "DET",
        ("nhl", "elo", "detroit"): "DET",
        ("nhl", "elo", "edmonton oilers"): "EDM",
        ("nhl", "elo", "edmonton"): "EDM",
        ("nhl", "elo", "florida panthers"): "FLA",
        ("nhl", "elo", "florida"): "FLA",
        ("nhl", "elo", "panthers"): "FLA",
        ("nhl", "elo", "los angeles kings"): "LAK",
        ("nhl", "elo", "los angeles"): "LAK",
        ("nhl", "elo", "losangeles"): "LAK",
        ("nhl", "elo", "minnesota wild"): "MIN",
        ("nhl", "elo", "minnesota"): "MIN",
        ("nhl", "elo", "montreal canadiens"): "MTL",
        ("nhl", "elo", "montréal canadiens"): "MTL",
        ("nhl", "elo", "montreal"): "MTL",
        ("nhl", "elo", "nashville predators"): "NSH",
        ("nhl", "elo", "nashville"): "NSH",
        ("nhl", "elo", "new jersey devils"): "NJD",
        ("nhl", "elo", "new jersey"): "NJD",
        ("nhl", "elo", "newjersey"): "NJD",
        ("nhl", "elo", "new york islanders"): "NYI",
        ("nhl", "elo", "ny islanders"): "NYI",
        ("nhl", "elo", "nyislanders"): "NYI",
        ("nhl", "elo", "new york rangers"): "NYR",
        ("nhl", "elo", "ny rangers"): "NYR",
        ("nhl", "elo", "nyrangers"): "NYR",
        ("nhl", "elo", "ottawa senators"): "OTT",
        ("nhl", "elo", "ottawa"): "OTT",
        ("nhl", "elo", "philadelphia flyers"): "PHI",
        ("nhl", "elo", "philadelphia"): "PHI",
        ("nhl", "elo", "pittsburgh penguins"): "PIT",
        ("nhl", "elo", "pittsburgh"): "PIT",
        ("nhl", "elo", "san jose sharks"): "SJS",
        ("nhl", "elo", "san jose"): "SJS",
        ("nhl", "elo", "sanjose"): "SJS",
        ("nhl", "elo", "seattle kraken"): "SEA",
        ("nhl", "elo", "seattle"): "SEA",
        ("nhl", "elo", "seattlekraken"): "SEA",
        ("nhl", "elo", "st. louis blues"): "STL",
        ("nhl", "elo", "st. louis"): "STL",
        ("nhl", "elo", "st.louis"): "STL",
        ("nhl", "elo", "st louis blues"): "STL",
        ("nhl", "elo", "tampa bay lightning"): "TBL",
        ("nhl", "elo", "tampa bay"): "TBL",
        ("nhl", "elo", "tampabay"): "TBL",
        ("nhl", "elo", "toronto maple leafs"): "TOR",
        ("nhl", "elo", "toronto"): "TOR",
        ("nhl", "elo", "utah hockey club"): "UTA",
        ("nhl", "elo", "utah"): "UTA",
        ("nhl", "elo", "utah mammoth"): "UTA",
        ("nhl", "elo", "vancouver canucks"): "VAN",
        ("nhl", "elo", "vancouver"): "VAN",
        ("nhl", "elo", "vegas golden knights"): "VGK",
        ("nhl", "elo", "vegas"): "VGK",
        ("nhl", "elo", "washington capitals"): "WSH",
        ("nhl", "elo", "washington"): "WSH",
        ("nhl", "elo", "winnipeg jets"): "WPG",
        ("nhl", "elo", "winnipeg"): "WPG",
        # MLB mappings - abbreviations to full names
        ("mlb", "kalshi", "az"): "Arizona Diamondbacks",
        ("mlb", "kalshi", "ari"): "Arizona Diamondbacks",
        ("mlb", "kalshi", "arizona"): "Arizona Diamondbacks",
        ("mlb", "kalshi", "ath"): "Athletics",
        ("mlb", "kalshi", "atl"): "Atlanta Braves",
        ("mlb", "kalshi", "atlanta hawks"): "Atlanta Braves",
        ("mlb", "kalshi", "bal"): "Baltimore Orioles",
        ("mlb", "kalshi", "bos"): "Boston Red Sox",
        ("mlb", "kalshi", "boston bruins"): "Boston Red Sox",
        ("mlb", "kalshi", "chc"): "Chicago Cubs",
        ("mlb", "kalshi", "cws"): "Chicago White Sox",
        ("mlb", "kalshi", "cincinnati"): "Cincinnati Reds",
        ("mlb", "kalshi", "cin"): "Cincinnati Reds",
        ("mlb", "kalshi", "cle"): "Cleveland Guardians",
        ("mlb", "kalshi", "cleveland cavaliers"): "Cleveland Guardians",
        ("mlb", "kalshi", "col"): "Colorado Rockies",
        ("mlb", "kalshi", "colorado avalanche"): "Colorado Rockies",
        ("mlb", "kalshi", "det"): "Detroit Tigers",
        ("mlb", "kalshi", "hou"): "Houston Astros",
        ("mlb", "kalshi", "houston"): "Houston Astros",
        ("mlb", "kalshi", "kc"): "Kansas City Royals",
        ("mlb", "kalshi", "laa"): "Los Angeles Angels",
        ("mlb", "kalshi", "lad"): "Los Angeles Dodgers",
        ("mlb", "kalshi", "mia"): "Miami Marlins",
        ("mlb", "kalshi", "mil"): "Milwaukee Brewers",
        ("mlb", "kalshi", "min"): "Minnesota Twins",
        ("mlb", "kalshi", "nym"): "New York Mets",
        ("mlb", "kalshi", "nyy"): "New York Yankees",
        ("mlb", "kalshi", "oak"): "Athletics",
        ("mlb", "kalshi", "phi"): "Philadelphia Phillies",
        ("mlb", "kalshi", "philadelphia flyers"): "Philadelphia Phillies",
        ("mlb", "kalshi", "pit"): "Pittsburgh Pirates",
        ("mlb", "kalshi", "pittsburgh penguins"): "Pittsburgh Pirates",
        ("mlb", "kalshi", "sd"): "San Diego Padres",
        ("mlb", "kalshi", "sea"): "Seattle Mariners",
        ("mlb", "kalshi", "seattle kraken"): "Seattle Mariners",
        ("mlb", "kalshi", "sf"): "San Francisco Giants",
        ("mlb", "kalshi", "stl"): "St. Louis Cardinals",
        ("mlb", "kalshi", "st. louis blues"): "St. Louis Cardinals",
        ("mlb", "kalshi", "st louis blues"): "St. Louis Cardinals",
        ("mlb", "kalshi", "tb"): "Tampa Bay Rays",
        ("mlb", "kalshi", "tex"): "Texas Rangers",
        ("mlb", "kalshi", "texas"): "Texas Rangers",
        ("mlb", "kalshi", "tor"): "Toronto Blue Jays",
        ("mlb", "kalshi", "toronto maple leafs"): "Toronto Blue Jays",
        ("mlb", "kalshi", "wsn"): "Washington Nationals",
        ("mlb", "kalshi", "washington capitals"): "Washington Nationals",
        ("mlb", "kalshi", "wsh"): "Washington Nationals",
        # Ligue 1
        ("ligue1", "kalshi", "psg"): "PSG",
        ("ligue1", "kalshi", "mar"): "Marseille",
        ("ligue1", "kalshi", "lyo"): "Lyon",
        ("ligue1", "kalshi", "asm"): "Monaco",
        ("ligue1", "kalshi", "lil"): "Lille",
        ("ligue1", "kalshi", "nic"): "Nice",
        ("ligue1", "kalshi", "ren"): "Rennes",
        ("ligue1", "kalshi", "rcl"): "Lens",
        ("ligue1", "kalshi", "rei"): "Reims",
        ("ligue1", "kalshi", "mpl"): "Montpellier",
        ("ligue1", "kalshi", "fcn"): "Nantes",
        ("ligue1", "kalshi", "rcs"): "Strasbourg",
        ("ligue1", "kalshi", "tfc"): "Toulouse",
        ("ligue1", "kalshi", "fcl"): "Lorient",
        ("ligue1", "kalshi", "hac"): "Le Havre",
        ("ligue1", "kalshi", "fcm"): "Metz",
        ("ligue1", "kalshi", "ang"): "Angers",
        ("ligue1", "kalshi", "stb"): "Brest",
        ("ligue1", "kalshi", "aux"): "Auxerre",
        ("ligue1", "kalshi", "ste"): "Saint-Etienne",
        ("ligue1", "kalshi", "tro"): "Troyes",
        ("ligue1", "kalshi", "cle"): "Clermont",
        ("ligue1", "kalshi", "aja"): "Ajaccio",
        ("ligue1", "kalshi", "par"): "Paris FC",
        ("ligue1", "kalshi", "bor"): "Bordeaux",
        # Ligue 1 Elo/CSV
        ("ligue1", "elo", "paris saint-germain"): "PSG",
        ("ligue1", "elo", "paris sg"): "PSG",
        ("ligue1", "elo", "olympique de marseille"): "Marseille",
        ("ligue1", "elo", "olympique marseille"): "Marseille",
        ("ligue1", "elo", "marseille"): "Marseille",
        ("ligue1", "elo", "olympique lyonnais"): "Lyon",
        ("ligue1", "elo", "lyon"): "Lyon",
        ("ligue1", "elo", "as monaco"): "Monaco",
        ("ligue1", "elo", "monaco"): "Monaco",
        ("ligue1", "elo", "lille osc"): "Lille",
        ("ligue1", "elo", "lille"): "Lille",
        ("ligue1", "elo", "ogc nice"): "Nice",
        ("ligue1", "elo", "nice"): "Nice",
        ("ligue1", "elo", "stade rennais"): "Rennes",
        ("ligue1", "elo", "rennes"): "Rennes",
        ("ligue1", "elo", "rc lens"): "Lens",
        ("ligue1", "elo", "lens"): "Lens",
        ("ligue1", "elo", "stade de reims"): "Reims",
        ("ligue1", "elo", "reims"): "Reims",
        ("ligue1", "elo", "montpellier hsc"): "Montpellier",
        ("ligue1", "elo", "montpellier"): "Montpellier",
        ("ligue1", "elo", "fc nantes"): "Nantes",
        ("ligue1", "elo", "nantes"): "Nantes",
        ("ligue1", "elo", "rc strasbourg"): "Strasbourg",
        ("ligue1", "elo", "strasbourg"): "Strasbourg",
        ("ligue1", "elo", "toulouse fc"): "Toulouse",
        ("ligue1", "elo", "toulouse"): "Toulouse",
        ("ligue1", "elo", "fc lorient"): "Lorient",
        ("ligue1", "elo", "lorient"): "Lorient",
        ("ligue1", "elo", "le havre ac"): "Le Havre",
        ("ligue1", "elo", "le havre"): "Le Havre",
        ("ligue1", "elo", "fc metz"): "Metz",
        ("ligue1", "elo", "metz"): "Metz",
        ("ligue1", "elo", "angers sco"): "Angers",
        ("ligue1", "elo", "angers"): "Angers",
        ("ligue1", "elo", "stade brestois"): "Brest",
        ("ligue1", "elo", "brest"): "Brest",
        ("ligue1", "elo", "aj auxerre"): "Auxerre",
        ("ligue1", "elo", "auxerre"): "Auxerre",
        ("ligue1", "elo", "st etienne"): "Saint-Etienne",
        ("ligue1", "elo", "saint-etienne"): "Saint-Etienne",
        ("ligue1", "elo", "estac troyes"): "Troyes",
        ("ligue1", "elo", "troyes"): "Troyes",
        ("ligue1", "elo", "clermont foot"): "Clermont",
        ("ligue1", "elo", "clermont"): "Clermont",
        ("ligue1", "elo", "ac ajaccio"): "Ajaccio",
        ("ligue1", "elo", "ajaccio"): "Ajaccio",
        ("ligue1", "elo", "fc bordeaux"): "Bordeaux",
        ("ligue1", "elo", "bordeaux"): "Bordeaux",
        ("ligue1", "elo", "paris fc"): "Paris FC",
    }
    _KALSHI_CANONICAL_NAMES = {
        "epl": {
            "Arsenal": "Arsenal",
            "Aston Villa": "Aston Villa",
            "Bournemouth": "Bournemouth",
            "Brentford": "Brentford",
            "Brighton": "Brighton and Hove Albion",
            "Burnley": "Burnley",
            "Chelsea": "Chelsea",
            "Crystal Palace": "Crystal Palace",
            "Everton": "Everton",
            "Fulham": "Fulham",
            "Ipswich": "Ipswich Town",
            "Leeds": "Leeds United",
            "Leicester": "Leicester City",
            "Liverpool": "Liverpool",
            "Luton": "Luton Town",
            "Man City": "Manchester City",
            "Man United": "Manchester United",
            "Newcastle": "Newcastle United",
            "Nott'm Forest": "Nottingham Forest",
            "Norwich": "Norwich City",
            "Sheffield United": "Sheffield United",
            "Southampton": "Southampton",
            "Sunderland": "Sunderland",
            "Tottenham": "Tottenham Hotspur",
            "Watford": "Watford",
            "West Ham": "West Ham United",
            "Wolves": "Wolverhampton Wanderers",
        },
        "nba": {
            "ATL": "Atlanta Hawks",
            "BKN": "Brooklyn Nets",
            "BOS": "Boston Celtics",
            "CHA": "Charlotte Hornets",
            "CHI": "Chicago Bulls",
            "CLE": "Cleveland Cavaliers",
            "DAL": "Dallas Mavericks",
            "DEN": "Denver Nuggets",
            "DET": "Detroit Pistons",
            "GSW": "Golden State Warriors",
            "HOU": "Houston Rockets",
            "IND": "Indiana Pacers",
            "LAC": "Los Angeles Clippers",
            "LAL": "Los Angeles Lakers",
            "MEM": "Memphis Grizzlies",
            "MIA": "Miami Heat",
            "MIL": "Milwaukee Bucks",
            "MIN": "Minnesota Timberwolves",
            "NOP": "New Orleans Pelicans",
            "NYK": "New York Knicks",
            "OKC": "Oklahoma City Thunder",
            "ORL": "Orlando Magic",
            "PHI": "Philadelphia 76ers",
            "PHX": "Phoenix Suns",
            "POR": "Portland Trail Blazers",
            "SAC": "Sacramento Kings",
            "SAS": "San Antonio Spurs",
            "TOR": "Toronto Raptors",
            "UTA": "Utah Jazz",
            "WAS": "Washington Wizards",
        },
    }
    _RELATED_SPORT_FALLBACKS = {
        "ncaab": ("wncaab",),
        "wncaab": ("ncaab",),
    }

    @staticmethod
    def _finalize_resolution(context: NamingContext, resolved_name: str) -> str:
        """Apply source-specific normalization to a resolved name."""
        if context.source.lower() != "kalshi":
            return resolved_name

        sport_overrides = NamingResolver._KALSHI_CANONICAL_NAMES.get(
            context.sport.lower(), {}
        )
        return sport_overrides.get(resolved_name, resolved_name)

    @staticmethod
    def resolve(context: NamingContext) -> str:
        """Return canonical name for a team/player using NamingContext.

        Args:
            context: NamingContext object containing sport, source, and name

        Returns:
            Canonical name or original name if no mapping exists
        """
        if not context.name:
            return context.name

        key = context.to_key()

        # 1. Try exact match from mappings
        if key in NamingResolver._mappings:
            return NamingResolver._finalize_resolution(
                context, NamingResolver._mappings[key]
            )

        # 2. Try to find name in any source for this sport (cross-source fallback)
        for (s, src, n), canonical in NamingResolver._mappings.items():
            if s == context.sport.lower() and n == context.name.lower():
                return NamingResolver._finalize_resolution(context, canonical)

        # 3. Try explicit related-sport fallbacks only.
        # Generic cross-sport fallback caused collisions like NBA ATL -> Atlanta Braves.
        related_sports = NamingResolver._RELATED_SPORT_FALLBACKS.get(
            context.sport.lower(), ()
        )
        for related_sport in related_sports:
            for (s, src, n), canonical in NamingResolver._mappings.items():
                if s == related_sport and n == context.name.lower():
                    return NamingResolver._finalize_resolution(context, canonical)

        # 4. Return input unchanged if no mapping exists
        return context.name

    @staticmethod
    def add_mapping(
        context: NamingContext,
        canonical_name: str,
    ) -> None:
        """Add a mapping from raw name to canonical name.

        Args:
            context: NamingContext object containing sport, source, and raw name
            canonical_name: Canonical/normalized name
        """
        if not context.sport or not context.source or not context.name:
            raise ValueError("NamingContext must have sport, source, and name.")

        key = context.to_key()
        NamingResolver._mappings[key] = canonical_name
